### ISSUE TITLE
Make spark master HA via zookeeper

### ISSUE THREAD

**Issue by lnguyen** [cloudfoundry-community/bigdata-boshrelease#2]

**Comment by drnic** [comment]
@lnguyen you'll do this this weekend? :)

**Comment by cppforlife** [comment]
if you all are looking for a nice zookeeper release, there is one here: https://github.com/cppforlife/zookeeper-release. happy to change it to provide necessary features.

**Comment by drnic** [comment]
@cppforlife I'm having trouble with the maintainer merging PRs https://github.com/cppforlife/zookeeper-release/pull/1 ;) **Update** to be fair to you I don't think I ever saw an email notification for your 6 June comment, sorry.

**Comment by drnic** [comment]
@cppforlife I don't think @lnguyen or I are against delegating to zookeper-release. I think @lnguyen created this repo a fair while ago as a learning exercise on bosh links. I upgraded the CI pipeline + added automatic fetching of apache releases as new blobs.

I'd probably prefer it was split into many smaller releases; so in that case the zookeeper portion could be ignored in lieu of your zookeeper-release.

**Comment by cppforlife** [comment]
i see. well, if you all continue with it...

> I'd probably prefer it was split into many smaller releases
+1

**Comment by lnguyen** [comment]
lets close those now.. When I was creating this release I was wrestling between tons of smaller releases vs one big one. I don't have huge preference either way.
